import {definePluginEntry} from "openclaw/plugin-sdk/plugin-entry";
import {WorkspaceRegistry} from "@leeclaw/workspace-core";
import {resolvePromotionConfig} from "./lib/config.js";
import {promotionPrincipal} from "./lib/principal.js";
import {PromotionClient} from "./lib/client.js";
function required(params,key){const v=String(params?.[key]??"").trim();if(!v)throw new Error(`${key} is required`);return v;}
function workspace(options){return String(options.params?.workspaceId??"").trim()||undefined;}
function register(api,name,scope,handler){api.registerGatewayMethod(name,async options=>{try{options.respond(true,await handler(options));}catch(error){options.respond(false,{error:error instanceof Error?error.message:String(error)});}}, {scope,profileAccess:"required"});}
function without(params={},keys=[]){const out={...params};for(const key of keys)delete out[key];return out;}
export default definePluginEntry({id:"leeclaw-promotion",name:"LeeClaw Promotion",description:"Controlled Experience Promotion for reviewed Knowledge and shared Skill publication.",register(api){const config=resolvePromotionConfig(api.pluginConfig??{});const registry=new WorkspaceRegistry(config.workspaceRegistryPath,config.workspaceStatePath);const client=new PromotionClient(config);const principal=(options,role="viewer")=>promotionPrincipal(options.client,registry,workspace(options),role);register(api,"leeclaw.promotion.list","operator.read",o=>client.list(principal(o),o.params?.limit));register(api,"leeclaw.promotion.get","operator.read",o=>client.get(principal(o),required(o.params,"candidateId")));register(api,"leeclaw.promotion.create","operator.write",o=>client.create(principal(o,"viewer"),o.params?.candidate??without(o.params,["workspaceId"])));register(api,"leeclaw.promotion.recheck","operator.write",o=>client.recheck(principal(o,"viewer"),required(o.params,"candidateId")));register(api,"leeclaw.promotion.review","operator.admin",o=>client.review(principal(o,"admin"),required(o.params,"candidateId"),o.params?.review??without(o.params,["workspaceId","candidateId"])));register(api,"leeclaw.promotion.publish","operator.admin",o=>client.publish(principal(o,"admin"),required(o.params,"candidateId")));register(api,"leeclaw.promotion.rollback","operator.admin",o=>client.rollback(principal(o,"admin"),required(o.params,"candidateId"),o.params?.reason));}});
