package retrieval

import (
	"fmt"
	"strings"
	"cobraknowledge.local/cobra-knowledge/internal/model"
)
type Planner struct{Catalog SemanticCatalog}
func NewPlanner(c SemanticCatalog)*Planner{return &Planner{Catalog:c}}
var definitionWords=[]string{"什么是","定义","含义","概念","区别","解释"}
var reasonWords=[]string{"为什么","原因","依据","说明","如何判断","怎么判断","诊断","分析原因"}
var currentWords=[]string{"当前","现在","实时","最新","现状","目前"}
var schemaWords=[]string{"本体","类层级","domain","range","合法关系","允许关系","类型关系","schema"}
var complexWords=[]string{"综合","结合","影响哪些","怎么关联","路径","多跳","以及","同时","并且"}
func (p *Planner) Plan(req model.QueryRequest)model.RetrievalPlan{q:=strings.TrimSpace(req.Query);semantics:=model.QuerySemantics{Intent:"fact_query",Scope:cloneScope(req.Scope)};sourceReasons:=map[model.RetrievalSource]string{};for _,t:=range p.Catalog.Classes{if termMatches(q,t){semantics.MatchedClasses=append(semantics.MatchedClasses,t.ID)}};for _,t:=range p.Catalog.Properties{if termMatches(q,t){semantics.MatchedProperties=append(semantics.MatchedProperties,t.ID);for _,s:=range t.PreferredSources{sourceReasons[s]="命中属性‘"+t.Label+"’的来源策略"}}};for _,t:=range p.Catalog.Relations{if termMatches(q,t){semantics.MatchedRelations=append(semantics.MatchedRelations,t.ID)}};if containsAny(q,schemaWords){semantics.Intent="schema_query";sourceReasons[model.SourceOntologyGraph]="问题直接涉及本体、类型或关系约束"};if containsAny(q,definitionWords){semantics.Intent="definition";sourceReasons[model.SourceWikiRAG]="定义/解释问题需要文档知识";sourceReasons[model.SourceOntologyGraph]="定义/解释问题可使用正式语义定义"};if containsAny(q,reasonWords){semantics.Intent="diagnosis";sourceReasons[model.SourceEntityGraph]="诊断需要具体事实";sourceReasons[model.SourceWikiRAG]="诊断需要原因、依据和原文证据"};if containsAny(q,currentWords)&&len(semantics.MatchedProperties)>0{if propertyPrefers(p.Catalog,q,model.SourceBusinessData){sourceReasons[model.SourceBusinessData]="当前/实时属性按策略使用业务数据源"}};if len(sourceReasons)==0&&(len(semantics.MatchedClasses)>0||len(semantics.MatchedRelations)>0){sourceReasons[model.SourceEntityGraph]="命中结构化业务语义，优先实体事实图"};if len(sourceReasons)==0{semantics.Intent="knowledge_query";sourceReasons[model.SourceWikiRAG]="未命中稳定结构化语义，回退 Wiki/RAG"};order:=[]model.RetrievalSource{model.SourceBusinessData,model.SourceEntityGraph,model.SourceWikiRAG,model.SourceOntologyGraph};var steps []model.RetrievalStep;var reasons []string;parallelGroup:="";if len(sourceReasons)>1{parallelGroup="g1"};idx:=1;for _,source:=range order{reason,ok:=sourceReasons[source];if !ok{continue};steps=append(steps,model.RetrievalStep{ID:fmt.Sprintf("s%d",idx),Source:source,Operation:operationFor(source),Query:q,Purpose:reason,TargetClassIDs:append([]string(nil),semantics.MatchedClasses...),TargetPropertyIDs:append([]string(nil),semantics.MatchedProperties...),TargetRelationIDs:append([]string(nil),semantics.MatchedRelations...),ParallelGroup:parallelGroup});reasons=append(reasons,reason);idx++};complex:=containsAny(q,complexWords)&&len(steps)>1;return model.RetrievalPlan{Query:q,Mode:map[bool]string{true:"complex",false:"fast"}[complex],Semantics:semantics,Steps:steps,NeedArbitration:len(steps)>1||containsSource(steps,model.SourceBusinessData),NeedEvidence:containsSource(steps,model.SourceWikiRAG)||len(steps)>1,StopCondition:stopCondition(semantics.Intent),Reasons:reasons,RequiresLLMPlanning:complex}}
func operationFor(s model.RetrievalSource)string{switch s{case model.SourceBusinessData:return "query_live_data";case model.SourceEntityGraph:return "query_entities_relations";case model.SourceOntologyGraph:return "query_schema";default:return "search_knowledge"}}
func stopCondition(intent string)string{switch intent{case "fact_query":return "获得唯一可接受事实或明确冲突";case "diagnosis":return "获得事实、原因/依据及至少一条可追溯证据";case "schema_query":return "获得明确的类型/属性/关系定义与约束";case "definition":return "获得正式语义定义与足够解释性证据";default:return "检索结果足以回答且无关键证据缺口"}}
func propertyPrefers(c SemanticCatalog,q string,s model.RetrievalSource)bool{for _,p:=range c.Properties{if !termMatches(q,p){continue};for _,x:=range p.PreferredSources{if x==s{return true}}};return false}
func containsAny(q string,words []string)bool{l:=strings.ToLower(q);for _,w:=range words{if strings.Contains(l,strings.ToLower(w)){return true}};return false}
func containsSource(steps []model.RetrievalStep,s model.RetrievalSource)bool{for _,st:=range steps{if st.Source==s{return true}};return false}
func cloneScope(in map[string]string)map[string]string{if in==nil{return nil};out:=map[string]string{};for k,v:=range in{out[k]=v};return out}
