package ontology

import (
	"context"
	"fmt"
	"sort"
	"strconv"
	"strings"
	"time"

	"cobraknowledge.local/cobra-knowledge/internal/model"
)

type ClassPattern struct { Label string `json:"label"`; Count int `json:"count"`; Properties map[string]int `json:"properties"`; Examples []string `json:"examples,omitempty"` }
type PropertyPattern struct { Label string `json:"label"`; Domains map[string]int `json:"domains"`; DataTypes map[string]int `json:"data_types"`; Examples []string `json:"examples,omitempty"`; TotalSupport int `json:"total_support"` }
type RelationPattern struct { Label string `json:"label"`; DomainRange map[string]int `json:"domain_range"`; TotalSupport int `json:"total_support"` }
type PatternReport struct { Domain string `json:"domain"`; Classes []ClassPattern `json:"classes"`; Properties []PropertyPattern `json:"properties"`; Relations []RelationPattern `json:"relations"`; Warnings []string `json:"warnings,omitempty"` }
type SemanticSuggestions struct { ClassAliases map[string][]string `json:"class_aliases,omitempty"`; PropertyAliases map[string][]string `json:"property_aliases,omitempty"`; RelationAliases map[string][]string `json:"relation_aliases,omitempty"`; ParentByClass map[string]string `json:"parent_by_class,omitempty"`; MergeClasses [][]string `json:"merge_classes,omitempty"`; ReviewQuestions []string `json:"review_questions,omitempty"` }
type SemanticInducer interface { Induce(ctx context.Context, report PatternReport) (SemanticSuggestions,error) }
type NoopSemanticInducer struct{}
func (NoopSemanticInducer) Induce(context.Context, PatternReport) (SemanticSuggestions,error) { return SemanticSuggestions{},nil }
type DiscoveryService struct { Inducer SemanticInducer }
func NewDiscoveryService(inducer SemanticInducer)*DiscoveryService{if inducer==nil{inducer=NoopSemanticInducer{}};return &DiscoveryService{Inducer:inducer}}
func (s *DiscoveryService) Discover(ctx context.Context, graph model.GraphSnapshot)(model.Ontology,PatternReport,error){report:=Analyze(graph); suggestions,err:=s.Inducer.Induce(ctx,report); if err!=nil{return model.Ontology{},report,fmt.Errorf("semantic induction: %w",err)}; return BuildCandidate(report,suggestions),report,nil}
func Analyze(graph model.GraphSnapshot) PatternReport {
	classCounts:=map[string]int{}; classProps:=map[string]map[string]int{}; classExamples:=map[string][]string{}; propPatterns:=map[string]*PropertyPattern{}; entityByID:=map[string]model.Entity{}
	for _,entity:=range graph.Entities { typ:=clean(entity.BusinessType); if typ==""{typ="未分类实体"}; entityByID[entity.ID]=entity; classCounts[typ]++; if classProps[typ]==nil{classProps[typ]=map[string]int{}}; if len(classExamples[typ])<5{classExamples[typ]=append(classExamples[typ],entity.Name)}; for key,value:=range entity.Properties{key=clean(key); if key==""{continue}; classProps[typ][key]++; pp:=propPatterns[key]; if pp==nil{pp=&PropertyPattern{Label:key,Domains:map[string]int{},DataTypes:map[string]int{}};propPatterns[key]=pp}; pp.Domains[typ]++; dtype:=inferDataType(value); pp.DataTypes[dtype]++; pp.TotalSupport++; if len(pp.Examples)<5{pp.Examples=append(pp.Examples,fmt.Sprint(value))}} }
	relPatterns:=map[string]*RelationPattern{}; for _,rel:=range graph.Relations{src,srcOK:=entityByID[rel.SourceID];dst,dstOK:=entityByID[rel.TargetID];if !srcOK||!dstOK{continue};label:=clean(rel.BusinessType);if label==""{continue};rp:=relPatterns[label];if rp==nil{rp=&RelationPattern{Label:label,DomainRange:map[string]int{}};relPatterns[label]=rp};pair:=clean(src.BusinessType)+"\x00"+clean(dst.BusinessType);rp.DomainRange[pair]++;rp.TotalSupport++}
	report:=PatternReport{Domain:graph.Domain,Warnings:append([]string(nil),graph.Warnings...)}; for label,count:=range classCounts{report.Classes=append(report.Classes,ClassPattern{Label:label,Count:count,Properties:classProps[label],Examples:classExamples[label]})}; for _,pp:=range propPatterns{report.Properties=append(report.Properties,*pp)};for _,rp:=range relPatterns{report.Relations=append(report.Relations,*rp)};sort.Slice(report.Classes,func(i,j int)bool{return report.Classes[i].Label<report.Classes[j].Label});sort.Slice(report.Properties,func(i,j int)bool{return report.Properties[i].Label<report.Properties[j].Label});sort.Slice(report.Relations,func(i,j int)bool{return report.Relations[i].Label<report.Relations[j].Label});return report
}
func BuildCandidate(report PatternReport,suggestions SemanticSuggestions) model.Ontology {
	domain:=report.Domain; onto:=model.Ontology{ID:model.StableID("ont",domain,domain),Domain:domain,Version:"0.1.0-candidate",Status:model.StatusCandidate,CreatedAt:time.Now().UTC(),Metadata:map[string]string{"method":"bottom-up pattern induction with deterministic validation","runtime_dependency":"none","reference_method":"graph-native ontology discovery"}}
	classID:=map[string]string{}; for _,cp:=range report.Classes{id:=model.StableID("cls",domain,cp.Label);classID[cp.Label]=id;onto.Classes=append(onto.Classes,model.OntologyClass{ID:id,Label:cp.Label,Aliases:unique(suggestions.ClassAliases[cp.Label]),Support:cp.Count,Confidence:supportConfidence(cp.Count),Status:model.StatusCandidate})}
	for i:=range onto.Classes{parentLabel:=clean(suggestions.ParentByClass[onto.Classes[i].Label]);if parentLabel==""{continue};if pid,ok:=classID[parentLabel];ok{onto.Classes[i].ParentIDs=[]string{pid}}else{onto.ReviewQueue=append(onto.ReviewQueue,model.ReviewItem{ID:model.StableID("review",domain,"missing-parent\x00"+onto.Classes[i].Label),Kind:"hierarchy",SubjectIDs:[]string{onto.Classes[i].ID},Question:fmt.Sprintf("类型“%s”的候选父类“%s”不存在，是否需要新增或修正？",onto.Classes[i].Label,parentLabel),Risk:"medium",SuggestedBy:"semantic_inducer",Status:"pending"})}}
	for _,pp:=range report.Properties{domains,confidence:=dominantLabels(pp.Domains,pp.TotalSupport,0.80);domainIDs:=labelsToIDs(domains,classID);dtype:=dominantDataType(pp.DataTypes);onto.Properties=append(onto.Properties,model.DataProperty{ID:model.StableID("prop",domain,pp.Label),Label:pp.Label,Aliases:unique(suggestions.PropertyAliases[pp.Label]),DomainIDs:domainIDs,DataType:dtype,Support:pp.TotalSupport,Confidence:confidence,Status:model.StatusCandidate,RetrievalPolicy:&model.RetrievalPolicy{PreferredSources:[]string{string(model.SourceEntityGraph)},FreshnessMode:"change_driven",ConflictMode:"policy_then_time",RequireEvidence:true}});if len(domainIDs)==0{onto.ReviewQueue=append(onto.ReviewQueue,model.ReviewItem{ID:model.StableID("review",domain,"property-domain\x00"+pp.Label),Kind:"property_domain",Question:fmt.Sprintf("属性“%s”的归属类型不稳定，需要业务确认 Domain。",pp.Label),Risk:"medium",SuggestedBy:"pattern_analyzer",Status:"pending"})}}
	for _,rp:=range report.Relations{pair,count:=dominantPair(rp.DomainRange);parts:=strings.Split(pair,"\x00");var domains,ranges []string;confidence:=0.0;if rp.TotalSupport>0{confidence=float64(count)/float64(rp.TotalSupport)};if len(parts)==2&&confidence>=0.80{if id,ok:=classID[parts[0]];ok{domains=[]string{id}};if id,ok:=classID[parts[1]];ok{ranges=[]string{id}}};relID:=model.StableID("obj",domain,rp.Label);onto.Relations=append(onto.Relations,model.ObjectRelation{ID:relID,Label:rp.Label,Aliases:unique(suggestions.RelationAliases[rp.Label]),DomainIDs:domains,RangeIDs:ranges,Support:rp.TotalSupport,Confidence:confidence,Status:model.StatusCandidate});if len(domains)==0||len(ranges)==0{onto.ReviewQueue=append(onto.ReviewQueue,model.ReviewItem{ID:model.StableID("review",domain,"relation-domain-range\x00"+rp.Label),Kind:"relation_domain_range",SubjectIDs:[]string{relID},Question:fmt.Sprintf("关系“%s”的 Domain/Range 模式不稳定，需要业务确认。",rp.Label),Risk:"high",SuggestedBy:"pattern_analyzer",Status:"pending"})}}
	for _,group:=range suggestions.MergeClasses{if len(group)<2{continue};var ids []string;for _,label:=range group{if id,ok:=classID[label];ok{ids=append(ids,id)}};if len(ids)>=2{onto.ReviewQueue=append(onto.ReviewQueue,model.ReviewItem{ID:model.StableID("review",domain,"merge\x00"+strings.Join(group,"|")),Kind:"class_merge",SubjectIDs:ids,Question:"候选类型是否应合并："+strings.Join(group," / "),Risk:"high",SuggestedBy:"semantic_inducer",Status:"pending"})}}
	for _,q:=range suggestions.ReviewQuestions{onto.ReviewQueue=append(onto.ReviewQueue,model.ReviewItem{ID:model.StableID("review",domain,q),Kind:"semantic",Question:q,Risk:"medium",SuggestedBy:"semantic_inducer",Status:"pending"})};sort.Slice(onto.Classes,func(i,j int)bool{return onto.Classes[i].Label<onto.Classes[j].Label});sort.Slice(onto.Properties,func(i,j int)bool{return onto.Properties[i].Label<onto.Properties[j].Label});sort.Slice(onto.Relations,func(i,j int)bool{return onto.Relations[i].Label<onto.Relations[j].Label});return onto
}
func inferDataType(v interface{})string{switch x:=v.(type){case bool:return "boolean";case int,int32,int64,uint,uint32,uint64:return "integer";case float32,float64:return "number";case string:s:=strings.TrimSpace(x);if s=="true"||s=="false"||s=="是"||s=="否"{return "boolean"};if _,err:=strconv.ParseInt(s,10,64);err==nil{return "integer"};if _,err:=strconv.ParseFloat(strings.TrimSuffix(strings.TrimSuffix(s,"%"),"km"),64);err==nil{return "number"};if _,err:=time.Parse("2006-01-02",s);err==nil{return "date"};return "string";default:return "string"}}
func dominantDataType(counts map[string]int)string{best,max:="string",-1;for k,v:=range counts{if v>max||(v==max&&k<best){best,max=k,v}};return best}
func dominantLabels(counts map[string]int,total int,threshold float64)([]string,float64){if total<=0{return nil,0};type kv struct{k string;v int};var arr []kv;for k,v:=range counts{arr=append(arr,kv{k,v})};sort.Slice(arr,func(i,j int)bool{if arr[i].v==arr[j].v{return arr[i].k<arr[j].k};return arr[i].v>arr[j].v});if len(arr)==0{return nil,0};conf:=float64(arr[0].v)/float64(total);if conf<threshold{return nil,conf};return []string{arr[0].k},conf}
func dominantPair(counts map[string]int)(string,int){best,max:="",-1;for k,v:=range counts{if v>max||(v==max&&k<best){best,max=k,v}};return best,max}
func labelsToIDs(labels []string,ids map[string]string)[]string{out:=make([]string,0,len(labels));for _,label:=range labels{if id,ok:=ids[label];ok{out=append(out,id)}};return unique(out)}
func supportConfidence(n int)float64{if n<=0{return 0};if n>=20{return 0.98};if n>=10{return 0.94};if n>=5{return 0.88};if n>=2{return 0.78};return 0.65}
func clean(s string)string{return strings.TrimSpace(s)}
func unique(in []string)[]string{seen:=map[string]struct{}{};out:=make([]string,0,len(in));for _,s:=range in{s=clean(s);if s==""{continue};if _,ok:=seen[s];ok{continue};seen[s]=struct{}{};out=append(out,s)};sort.Strings(out);return out}
